name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-wazuh-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > id_rsa
          chmod 600 id_rsa
      - name: SSH into the swarm server
        run: ssh -i id_rsa root@13.51.170.18

      - name: Run WHOAMI
        run: whoami