name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-wazuh-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
      - name: Write private key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Trust server host key (pin it)
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.51.170.18 >> ~/.ssh/known_hosts

      - name: SSH
        shell: bash
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o IdentitiesOnly=yes \
              -o UserKnownHostsFile=~/.ssh/known_hosts \
              root@13.51.170.18

      - name: Verify SSH
        shell: bash
        run: |
          set -euo pipefail
          OUT="$(ssh -i ~/.ssh/id_rsa -o BatchMode=yes -o UserKnownHostsFile=~/.ssh/known_hosts -T root@13.51.170.18 'echo SSH_OK && whoami && hostname')"
          echo "$OUT"
          echo "$OUT" | grep -qx 'SSH_OK'
